/**
 * Task Plan DSL Type Definitions
 * 
 * These types define the structure of task plans generated by the planner.
 * All actions must conform to these types for the executor to process them.
 */

/**
 * Allowed action types in v1
 */
export type ActionType =
  | 'readFiles'
  | 'createFile'
  | 'writeFile'
  | 'moveFile'
  | 'extractText'
  | 'runPlaywrightTask'
  | 'noop';

/**
 * Base action interface
 */
export interface BaseAction {
  action: ActionType;
  description?: string;
}

/**
 * Read files from a path (file or directory)
 */
export interface ReadFilesAction extends BaseAction {
  action: 'readFiles';
  path: string;
  pattern?: string; // Optional glob pattern for filtering
}

/**
 * Create a new file
 */
export interface CreateFileAction extends BaseAction {
  action: 'createFile';
  path: string;
  content: string;
}

/**
 * Write content to an existing file (overwrites)
 */
export interface WriteFileAction extends BaseAction {
  action: 'writeFile';
  path: string;
  content: string;
}

/**
 * Move/rename a file
 */
export interface MoveFileAction extends BaseAction {
  action: 'moveFile';
  sourcePath: string;
  destinationPath: string;
}

/**
 * Extract text from previously read files
 */
export interface ExtractTextAction extends BaseAction {
  action: 'extractText';
  instructions: string; // What to extract/summarize
}

/**
 * Run a Playwright browser task (feature-gated)
 */
export interface RunPlaywrightTaskAction extends BaseAction {
  action: 'runPlaywrightTask';
  taskType: 'fetchPage' | 'extractData' | 'fillForm';
  url?: string;
  selectors?: string[];
  data?: Record<string, unknown>;
}

/**
 * No operation - used for planning/comments
 */
export interface NoopAction extends BaseAction {
  action: 'noop';
}

/**
 * Union type of all possible actions
 */
export type Action =
  | ReadFilesAction
  | CreateFileAction
  | WriteFileAction
  | MoveFileAction
  | ExtractTextAction
  | RunPlaywrightTaskAction
  | NoopAction;

/**
 * Complete task plan structure
 */
export interface TaskPlan {
  task: string; // User's original task description
  steps: Action[]; // Ordered list of actions
  requiresConfirmation: boolean; // Whether destructive actions are present
  estimatedSteps?: number; // Optional step count estimate
}

/**
 * Execution result for a single step
 */
export interface StepResult {
  stepIndex: number;
  action: ActionType;
  success: boolean;
  output?: unknown;
  error?: string;
  duration?: number; // milliseconds
}

/**
 * Complete execution result
 */
export interface ExecutionResult {
  plan: TaskPlan;
  steps: StepResult[];
  success: boolean;
  totalDuration: number; // milliseconds
  error?: string;
}

/**
 * Workspace configuration
 */
export interface WorkspaceConfig {
  workingDirectory: string;
  allowedPaths: string[]; // Paths the executor can access
  maxSteps: number;
  stepTimeout: number; // milliseconds
  playwrightEnabled: boolean;
}
